sitewomen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Admin paneli'
admin.site.index_title = 'Ayollar'

users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetView, PasswordChangeDoneView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from . import views


app_name = 'users'


urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change-done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name='users/password_reset_email.html',
                                                      success_url = reverse_lazy("users:password_reset_done")
                                                    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                                                      success_url = reverse_lazy("users:password_reset_complete")
                                                                                      ), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile')
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Login', 
                               widget=forms.TextInput(attrs={'class': 'form-input'})
                               )
    password = forms.CharField(label='Parol', 
                               widget=forms.PasswordInput(attrs={'class': 'form-input'})
                               )

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Login', 
                               widget=forms.TextInput(attrs={'class': 'form-input'})
                               )
    password1 = forms.CharField(label='Parol', 
                               widget=forms.PasswordInput(attrs={'class': 'form-input'})
                               )
    password2 = forms.CharField(label='Parolni qaytaring', 
                               widget=forms.PasswordInput(attrs={'class': 'form-input'})
                               )

    class Meta:
        model = get_user_model()
        fields = ('username', 'email','first_name', 'last_name', 'password1', 'password2')
        labels = {
            'username': 'Ismingiz',
            'email': 'Email',
            'first_name': 'Ismingiz',
            'last_name': 'Familiyangiz',
            'password1': 'Parol',
            'password2': 'Parolni qaytaring',
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.EmailInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-input'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-input'}),
        }

    def clean_password2(self):
        data = self.cleaned_data
        if data['password1'] != data['password2']:
            raise forms.ValidationError('Parollar bir xil emas')
        return data['password2']
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Bu email band')
        return email
    

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(label='Login', disabled=True, widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', disabled=True, widget=forms.EmailInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')
        labels = {
            'first_name': 'Ismingiz',
            'last_name': 'Familiyangiz',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label='New password confirmation', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.auth.forms import AuthenticationForm 
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .forms import LoginUserForm, ProfileUserForm, RegisterUserForm, UserPasswordChangeForm
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
 


app_name = 'users'


class LoginUser(LoginView):
    form_class = LoginUserForm # default-> AuthenticationForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Login'}


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    extra_context = {'title': 'Registratsiya'}


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Foydalanuvchi profili'}

    def get_success_url(self):
        return reverse_lazy('users:profile')
    
    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done') 
    template_name = 'users/password_change_form.html'

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Autorizatsiya</h1>
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    <div class='form-error'>{{ form.non_field_errors }}</div>
   {% for f in form %}
    <p><label class='form-label' for="{{ f.id_for_label }}"> {{ f.label }} </label> {{f}}</p>
    <div class='form-error'>{{ f.errors }}</div>
   {% endfor %}
    <p><input type="submit" value='Login'/></p> 
</form>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Parolni muvafaqqiyatli o'zgartirdingiz</h1>

<p>Siz muvafaqqiyatli parolni o'zgartirdingiz. <a href="{% url 'users:profile' %}">Profilga qaytish.</a></p>


{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Parol o'zgartirish</h1>

<form method="post">
    {% csrf_token %}
    <div class='form-error'>{{ form.non_field_errors }}</div>
   {% for f in form %}
    <p><label class='form-label' for="{{ f.id_for_label }}"> {{ f.label }} </label> {{f}}</p>
    <div class='form-error'>{{ f.errors }}</div>
   {% endfor %}

    <p><input type="submit" value="Parol o/'zagartirish"/></p> 
</form>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h1>Parol o'zgartirildi</h1>

<p>Tabriklaymiz! Siz muvafaqqiyatli parolni o'zgartirdingiz.Uni <a href="{% url 'users:profile' %}">sistemaga kirishingiz</a> uchun ishlating</p>


{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<h1>Yangi parol</h1>

<form method="post">
    {% csrf_token %}
    <div class='form-error'>{{ form.non_field_errors }}</div>
   {% for f in form %}
    <p><label class='form-label' for="{{ f.id_for_label }}"> {{ f.label }} </label> {{f}}</p>
    <div class='form-error'>{{ f.errors }}</div>
   {% endfor %}

    <p><input type="submit" value="Saqlamoq"/></p> 
</form>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Parolni tiklash </h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Parol qayta tiklash</h1>
<form method="post">
    {% csrf_token %}
   {% for f in form %}
    <p><label class='form-label' for="{{ f.id_for_label }}"> {{ f.label }} </label> {{f}}</p>
    <div class='form-error'>{{ f.errors }}</div>
   {% endfor %}
   
    <p><input type="submit" value='Email ga yuborish'/></p> 
</form>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>Profil</h1>

<form method="post">
    {% csrf_token %}
    <div class='form-error'>{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class='form-label' for="{{ f.id_for_label }}"> {{ f.label }}:  </label> {{f}}</p>
    <div class='form-error'>{{ f.errors }}</div>
   {% endfor %}
    <p><input type="submit" value='Saqlamoq'/></p>

</form>

<hr>
<p><a href="{% url 'users:password_change' %}">Parolni o'zgartirish</a></p>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    <div class='form-error'>{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class='form-label' for="{{ f.id_for_label }}"> {{ f.label }} </label> {{f}}</p>
    <div class='form-error'>{{ f.errors }}</div>
   {% endfor %}
    <p><input type="submit" value='Registratsiya'/></p>

</form>
{% endblock %}

users/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Hush kelibsiz</h1>

<p>Siz muvafaqqiyatli registratsiyaga qildingiz! Endi saytga kirish uchun login qiling.</p>

<p>
<a href="{% url 'users:login' %}">Kirish</a>
</p>

{% endblock %}